stages:
  - lint
  - test
  - build

lint:
  tags:
    - runner-beast
  image: node:20
  stage: lint
  before_script:
    - cd frontend || exit 1  
    - npm ci                  
  script:
    - npm run lint

test:
  tags:
    - runner-beast
  image: node:20
  stage: test
  before_script:
    - cd backend || exit 1
    - npm ci
    - npx prisma generate
  script:
    - npm run test

build:
  tags:
    - runner-beast
  image: node:20
  stage: build
  before_script:
    - cd frontend || exit 1
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/dist

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/
