stages:
  - lint
  - test  
  - build

lint:
  tags:
    - do-runner-new
  stage: lint
  before_script:
    - cd frontend || exit 1
    - npm install  
  script:
    - npm run lint
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

test:
  tags:
    - do-runner-new
  stage: test
  before_script:
    - cd backend || exit 1
    - npm install  
    - npx prisma generate --schema=./db/prisma/schema.prisma
  script:
    - npm run test
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build:
  tags:
    - do-runner-new
  stage: build
  before_script:
    - cd frontend || exit 1
    - npm install 
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/dist
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'