stages:
  - deploy

variables:
  NODE_ENV: production

deploy-backend:
  tags:
    - runner-beast-new
  stage: deploy
  script:
    - cd /home/deploy/app/beast-academy-app
    - git reset --hard
    - git clean -fd
    - git remote set-url origin https://oauth2:${GIT_ACCESS_TOKEN}@gitlab.informatika.org/FarhanRaditya/beast-academy.git
    - git pull origin main
    - cd backend
    - npm install
    - npx prisma generate --schema=./db/prisma/schema.prisma
    - sudo -u deploy pm2 restart beast-backend || sudo -u deploy pm2 start index.js --name "beast-backend"
    - sudo -u deploy pm2 save
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  when: manual
  allow_failure: false

deploy-frontend:
  tags:
    - runner-beast-new
  stage: deploy
  script:
    - cd /home/deploy/app/beast-academy-app
    - git reset --hard
    - git clean -fd
    - git remote set-url origin https://oauth2:${GIT_ACCESS_TOKEN}@gitlab.informatika.org/FarhanRaditya/beast-academy.git
    - git pull origin main
    - cd frontend
    - npm ci || npm install
    - npm install --save-dev vue-tsc typescript npm-run-all @vue/tsconfig
    - NODE_ENV=production npm run build-only || npm run vite build || npx vite build
    
    - sudo -u deploy pm2 restart beast-frontend || sudo -u deploy pm2 start "serve -s dist -l 5173" --name "beast-frontend"
    - sudo -u deploy pm2 save
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  when: manual
  allow_failure: false