stages:
  - lint
  - test
  - build

lint:
  image: node:20
  stage: lint
  before_script:
    - cd frontend; if (-not $?) { exit 1 }  # Perbaikan syntax PowerShell
    - npm install  # Ganti npm ci dengan npm install jika tidak ada package-lock.json
  script:
    - npm run lint

test:
  tags:
    - runner-beast
  image: node:20
  stage: test
  before_script:
    - cd backend; if (-not $?) { exit 1 }  # Perbaikan syntax PowerShell
    - npm install  # Ganti npm ci dengan npm install jika tidak ada package-lock.json
    - npx prisma generate
  script:
    - npm run test

build:
  image: node:20
  stage: build
  before_script:
    - cd frontend; if (-not $?) { exit 1 }  # Perbaikan syntax PowerShell
    - npm install  # Ganti npm ci dengan npm install jika tidak ada package-lock.json
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/dist
