stages:
  - deploy

deploy:
  tags:
    - runner-beast-new
  stage: deploy
  script:
    # Konfigurasi git credential helper
    - git config --global credential.helper store
    - echo "https://${GIT_ACCESS_TOKEN}:@gitlab.informatika.org" > ~/.git-credentials
    
    # Fix permissions sebelum menjalankan script
    - sudo chown -R deploy:deploy /home/deploy/app/beast-academy-app/
    
    # Jalankan script deployment
    - sudo -u deploy /home/deploy/deploy-app.sh
    
    # Bersihkan credentials
    - rm ~/.git-credentials
  rules:
    - if: $CI_COMMIT_BRANCH == "main"