stages:
  - deploy

deploy:
  tags:
    - runner-beast-new
  stage: deploy
  script:
    # Tambahkan credentials Git
    - git config --global credential.helper store
    - echo "https://${GIT_ACCESS_TOKEN}:@gitlab.informatika.org" > ~/.git-credentials
    
    # Jalankan script deployment sebagai user deploy
    - sudo -u deploy /home/deploy/deploy-app.sh
    
    # Bersihkan credentials
    - rm ~/.git-credentials
  rules:
    - if: $CI_COMMIT_BRANCH == "main"