services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: maindb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./backend/db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
